### ISSUE TITLE
PHP 7 only, in 2017, is not a good idea.

### ISSUE THREAD

**Issue by vincent-guesnard** [Josantonius/PHP-MimeType#2]
Hello,

Since there is millions of systems which are PHP 5 only (at least until the end of 2017 - because of native PHP support from Debian 8 - the latest stable released of Debian - which run now, PHP 5.6.29).

I advice you to make your library PHP 5.6 compliant, by using with awesome one  : 

if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
    // PHP7 only stuff
}

Then, there is some rewriting to do :  

- declare(strict_types=1); (PHP 7 only)
- remove : :type from static functions (PHP 7 only) - i advice you to completely remove this if you won't deal with 2 classes
- inside getMimeFromExtension, change for : return (isset(static::$mimeTypes[$ext]) ? static::$mimeTypes[$ext] : "undefined"); (?? is PHP 7 only)

I'm currently rewriting all your functions to make it works under PHP 5.6. I will be maybe fork it on Github if i got times.

**Comment by Josantonius** [comment]
Honestly, I was aware of it when I did, I just thought of myself :sweat_smile: 

But, just today I wanted to use some of my libraries to create a Wordpress plugin and I understood that it had been a mistake to limit them to PHP7. Too hasty...

So I've decided to make them compatible with PHP 5.6 or higher and do not use the declarations type or return of the null coalescing operator for the moment.

Thank you for your recommendations and help. ;)
